# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
baseurl: "" # the subpath of your site, e.g. /blog
url: "kevin-middleton.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kevin Middleton
user_description: Hi there! If you're reading this then it probably isn't by chance and you'd like to know a bit more about who I am.<br><br>Ever since I can remember I've been interested in new and innovative technologies. My first computer ran Windows 95 and at 4 years old I already had a job in IT support. I was 7 when I received my GameBoy Color and that is where my love of video games has stemmed from; later at age 14 I created and ran an online forum centered around online gaming that attracted over 200 active users; it was around this time I started getting involved in learning Photoshop.<br><br>Growing up, I've had many ideas of what type of career path I wanted to follow; scientist, video game programmer, graphic designer. I only realized in my final year of school what I really wanted to do; become an user experience designer. I've always appreciated good user centered design, even before I knew what it was. In fact, it wasn't until I took a Human-Computer Interaction course in college that I found out that UX designers even existed. I already had a background in understanding what makes good and bad UX as well as designing it, so the process came natrually to me. I've been enjoying learning new UX tools and ideologies since.
education: Central Connecticut State University<br>Tunxis Community College
user_title: Web Developer, Aspiring UX Designer
email: kevinmiddleton@my.ccsu.edu
twitter_username: Link2999
github_username:  Kevin-Middleton
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
