# Site settings
title: Kevin Middleton
description: Kevin Middleton
baseurl: "" # the subpath of your site, e.g. /blog
url: "kevin-middleton.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kevin Middleton
user_description: Hi there! My name is Kevin and I live in Bristol, Connecticut. If you're reading this, then it probably isn't by chance and you'd like to know a bit more about who I am.<br><br>Ever since I can remember I've been interested in new and innovative technologies. My first computer ran Windows 95 and at 4 years old I already had a job in IT support. I was 7 when I received my GameBoy Color and that is where my love of video games has stemmed from; later at age 14 I created and ran an online forum centered around that passion that had attracted over 200 active users; around this time was when I started getting involved in learning Photoshop and getting to know the ins and outs of different content management systems.<br><br>Growing up, I've had many ideas of what type of career path I wanted to follow later in life; rocket scientist, video game programmer, graphic designer. I only realized in my final year of school what I really wanted to do, and that was to become an user experience designer. I've always appreciated good user centered design, even before I knew what it was. In fact, it wasn't until I took a Human-Computer Interaction course in college that I found out that UX careers even existed. I already had a background in understanding what makes good and bad UX as well as designing it, so the process came natrually to me. I've been enjoying learning new UX tools and ideologies since.<br><br>In my free time you'll most likely be able to find me online reading up about the latest technologies and security vulnerabilities that affect them, watching the latest Netflix hit, or playing a video game with a deep and engaging story. 
education: Central Connecticut State University (2013-2016) <br>Tunxis Community College (2010-2012)
user_title: Web Developer, Aspiring UX Designer
email: kevinmiddleton@my.ccsu.edu
twitter_username: Link2999
github_username:  Kevin-Middleton
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
